version: "3.1"
services:
  # PHP Service
  php-fpm:
    image: php:8.0.2-fpm
    container_name: sde
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
